[package]
name = "Goldengrove"
version = "0.1.0"
edition = "2021"
authors = ["Nathan Douglas <github@darkdell.net>"]

[lib]
name = "goldengrove"
path = "src/lib.rs"

[[bin]]
name = "goldengrove"
path = "src/main.rs"

[dependencies]
